# Numpy

In [2]:
%conda install numpy

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.3
  latest version: 4.11.0

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /home/studio-lab-user/.conda/envs/default

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libblas-3.9.0              |13_linux64_openblas          12 KB  conda-forge
    libcblas-3.9.0             |13_linux64_openblas          12 KB  conda-forge
    libgfortran-ng-11.2.0      |      h69a702a_13          19 KB  conda-forge
    libgfortran5-11.2.0        |      h5c6108e_13         1.7 MB  conda-forge
    liblapack-3.9.0            |13_linux64_openblas          12 KB  conda-forge
    libopenblas-0.3.18         |pthreads_h8fe5266_0         9.6 MB  conda-forge
    numpy-1.22.3               |   py39h18676bf_0       

In [2]:
import numpy as np

In [4]:
# 1 * 15 boyutunda array 
dizi = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])
dizi

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [6]:
# array'in boyutuna bakalım
dizi.shape # shape şekil demek, reshape ise yeniden şekillendirme

(15,)

In [7]:
dizi2 = dizi.reshape(3,5) # 1 * 15 lik dizimizi yeniden şekillendirerek 3*5 boyutunda diziye çeviriyoruz sonra da dizi2 ye atıyoruz.

In [9]:
dizi2 # orijinal dizimizi 3 satır 5 sutundan oluşan diziye dönüştürüldü.

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [10]:
print('şekil : ', dizi2.shape)
print('Boyut : ', dizi2.ndim) # ndim kaç boyutlu olduğunu söyler 

şekil :  (3, 5)
Boyut :  2


In [11]:
print('Veri Tipi : ', dizi2.dtype.name) # array içerisinde bulunan verinin tipi
print('Boy : ', dizi2.size) # size array'in boyunu söyler.

Veri Tipi :  int64
Boy :  15


In [12]:
# arrayin tipi
print('type : ', type(dizi2))

type :  <class 'numpy.ndarray'>


In [13]:
# sonuç nunpy kütüpanesinde çok boyutlu bir dizi olduğunudur (nunpy.ndarray)

In [15]:
# 2 boyutlu bir dizi oluşturalım.
dizi2D = np.array([[1 ,2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]])
dizi2D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
# sıfırlardan oluşan array oluşturmak da mümkün
sifir_dizi = np.zeros((3,4)) # 3 satır 4 sütundan oluşan dizi
sifir_dizi

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
# birlerden oluşan array oluşturmak için
birler_dizi = np.ones((3,4)) # 1 ler den oluşan 3 satır ve 4 sutundan oluşan array
birler_dizi

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
# boş bir array de oluşturabiliriz.
bos_dizi = np.empty((2,2))
bos_dizi

array([[4.67534458e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

In [16]:
# arange(x, y, basamak) x'den başlayarak y'ye kadar (y dahil değil) basamak sayısı kadar arttırarak array oluşturur.
dizi_aralik = np.arange(10, 50, 5)
dizi_aralik

array([10, 15, 20, 25, 30, 35, 40, 45])

In [18]:
# linspace(x, y, basamak) x ile y arasında basamak sayısı kadar olacak şekilde dizi oluştur
dizi_bosluk = np.linspace(11, 20, 5)
dizi_bosluk

array([11.  , 13.25, 15.5 , 17.75, 20.  ])

## Numpy temel operasyonlar

In [19]:
import numpy as np

In [20]:
# matematiksel ifadeler için 2 dizi oluşturalım
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a)
print("")
print(b)

[1 2 3]

[4 5 6]


In [21]:
print(a + b)
print(a - b) 
print(a**2)# dizinin kendisiyle çarpımı. yani karesi

[5 7 9]
[-3 -3 -3]
[1 4 9]


In [23]:
# filtreleme
a<2 # a dizisinin içindeki tüm elemanları 2den küçük mü diye kontrol eder

array([ True, False, False])

In [25]:
# Hadamard çarpımı ve matris çarpımı için 2 tane array oluşturalım
a = np.array([[1, 2, 3],[4, 5, 6]])
b = np.array([[1, 2, 3],[4, 5, 6]])



In [26]:
# Hadamard çarpımı
print(a*b)

[[ 1  4  9]
 [16 25 36]]


In [29]:
#transpos
#matris çarpımı
print(a)
print("")
print(b.T) # b'nin transpos unu alıyoruz deviriyoruz. yani 2 satır 3 sutundan 3 satır 2 sutuna çeviriyoruz
print("")
c = a.dot(b.T)# a'nın tüm satırlarını b'nin ilk sütunlarınlarınçarpıp toplayarak c'ye atar. yani 1*1 + 2*2 + 3*3 = 14 , 1*4 + 2*5 + 3*6 = 32 sonra a'nın 2. satırı ile b'nin sütunlarını çarp topla 
print(c)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[14 32]
 [32 77]]


In [30]:
# dizinin tüm elemanlarını toıplama
print(a)
a.sum() # bu kadar :)

[[1 2 3]
 [4 5 6]]


21

In [31]:
# dizinin en büyük değerini bulma
a.max()

6

In [32]:
# dizinin en küçük değerini bulma
a.min()

1

In [33]:
# dizinin satırlarını toplama
a.sum(axis=1) # axis =1 ise satırlar

array([ 6, 15])

In [35]:
# dizinin sütünlarını toplama
a.sum(axis=0) # axis = 0 ise sütun toplamları

array([5, 7, 9])

In [36]:
# dizinin karekökünü bulma
a = np.array([[1, 2, 3],[4, 5, 6]])
print(a)
np.sqrt(a) # a dizisinin karekökünü al. 

[[1 2 3]
 [4 5 6]]


array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [37]:
# dizinin karesini bulma
np.square(a) # a dizisinin karesini alır

array([[ 1,  4,  9],
       [16, 25, 36]])

In [38]:
# rastgele sayı üretme [0,1] arasında sürekli üniform dağılım 
rastgele_dizi = np.random.random((3,3))
rastgele_dizi

array([[0.66785762, 0.81706931, 0.38624222],
       [0.0976797 , 0.21769011, 0.99855556],
       [0.12846137, 0.1174548 , 0.25476092]])

## Indeksleme ve Dilimleme

In [39]:
import numpy as np

In [40]:
dizi = np.array([1,2,3,4,5,6,7])

In [41]:
# dizinin 1. elemanı yani sıfırncı indekste bulunan elemanı
dizi[0]

1

In [42]:
# dizinin ilk 4 elemanı
dizi[:4]

array([1, 2, 3, 4])

In [43]:
# dizinin tersi
dizi[::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [48]:
dizi_2D = np.array([[1,2,3,4,5],[6,7,8,9,10]]) # 2 boyutlu dizilerde indisleme ve dilimleme
dizi_2D

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [49]:
# dizinin 1. satır ve 1.sütunun da bulunan eleman; indisler saymaya sıfırdan başlar
dizi_2D[1,1]

7

In [50]:
# dizinin 1.sütununun tüm satırı
dizi_2D[:,1]

array([2, 7])

In [51]:
# dizinin 1. satırının 1.2.3. elemanı
dizi_2D[1,1:4]

array([7, 8, 9])

In [52]:
# dizinin son satırının tüm sutunları
dizi_2D[-1,:]

array([ 6,  7,  8,  9, 10])

In [54]:
# dizinin son sütununun tüm satırları
dizi_2D[:,-1]

array([ 5, 10])

## Şekil Manipülasyonu ve Dizileri İstifleme

In [55]:
import numpy as np

In [56]:
dizi_2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
dizi_2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
# vektör haline getirme
vektor = dizi_2D.ravel() # tek dizi haline getirmek için ravel fonksiyonu kkullanılır
vektor

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
vektor.reshape(3,3) # tekrar parçalıyoruz


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
# dizilerde satırları sütuna sütunları satıra çevirme işlemi için transpose yapılır
dizi_2D.T # .T bukadar :)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [67]:
dizi1 = np.array([[1,2],[3,4]])
dizi1

array([[1, 2],
       [3, 4]])

In [68]:
dizi2 = np.array([[-1,-2],[-3,-4]])
dizi2

array([[-1, -2],
       [-3, -4]])

In [70]:
# 2 dizi'yi allt alta istiflemek için vstack
dizi_dikey = np.vstack((dizi1,dizi2))
dizi_dikey

array([[ 1,  2],
       [ 3,  4],
       [-1, -2],
       [-3, -4]])

In [71]:
# 2 dizi yi yan yana istiflemek için hstack()
yatay_dizi = np.hstack((dizi1,dizi2))
yatay_dizi

array([[ 1,  2, -1, -2],
       [ 3,  4, -3, -4]])